name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        make install
    - name: Lynt with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
            
        # Runs a single command using the runners shell
        #- name: Run make command
        #  run: make hello
